apiVersion: v1
kind: Pod
metadata:
  labels:
    run: k8s
  name: k8s
spec:
  containers:
  - image: nginx
    name: k8s
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
