apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ak8s
  name: ak8s
spec:
  containers:
  - image: nginx
    name: ak8s
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
